In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
df = pd.read_csv(r"E:\ML\Useful data\Bengaluru_House_Data.csv")
df.tail(8)

,area_type,availability,location,size,total_sqft,bath,balcony,price
13312,Super built-up Area,Ready To Move,Bellandur,2,1262,2.0,2.0,47.0
13313,Super built-up Area,Ready To Move,Uttarahalli,3,1345,2.0,1.0,57.0
13314,Super built-up Area,Ready To Move,Green Glen Layout,3,1715,3.0,3.0,112.0
13315,Built-up Area,Ready To Move,Whitefield,5,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4,3600,5.0,NaN,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1,550,1.0,1.0,17.0